'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ArrowLeft,ArrowRight,Ghost,Footprints,Volume2,VolumeX,Users,UserRound,ChevronLeft,Check,LoaderCircle} from 'lucide-react';
import {CONTROLLER_ROSTER} from '@/lib/controller-roster.mjs';
const messages:Record<string,string>={SESSION_NOT_FOUND:'This session is unavailable. Use the code on the event computer.',CHARACTER_TAKEN:'That character was just selected. Choose another.',CHOOSE_CHARACTER:'Choose an available character.',NAME_REQUIRED:'Enter your name.',CONTROLLER_UNAVAILABLE:'Connection interrupted. Trying again.',HOST_REQUIRED:'Only the session host can change this.',LOBBY_FULL:'All human places are filled.',MATCH_STARTED:'The session has started. The host can return everyone to the lobby.',TOO_MANY_PLAYERS:'More people have joined than this setting allows.',WAITING_FOR_PLAYERS:'Waiting for the selected number of people to join.',UNREAL_OFFLINE:'The event computer is disconnected.',UNREAL_NOT_READY:'Press Play in the event computer’s Unreal editor first.',INVALID_SOS:'Choose a living guest and a message.',SOS_NOT_AVAILABLE:'You can send a message during the choice window.',RECIPIENT_UNAVAILABLE:'That guest cannot receive your message.',SOS_ALREADY_SENT:'You have already sent a message this round.',SOS_EXPIRED:'That request is no longer available.'};
const sosText:Record<string,string>={come_get_me:'Come get me',found_camera:'I found the camera',exit_blocked:'The exit is blocked'};
const roomNames:Record<string,string>={entrance:'Entrance Hall',hall:'Connecting Hall',gallery:'Painting Gallery',library:'Library',exit:'Rear Service Exit',portrait:'Grand Portrait Gallery',sculpture:'Sculpture Vault',archive:'Archive Library',conservation:'Conservation Lab',study:"Curator’s Study",sealed:'Sealed Exhibition Room',mirrors:'Hall of Mirrors'};
function Portrait({index,className=''}:{index:number;className?:string}){return <div className={`cast-portrait ${className}`} style={{backgroundPosition:`${(index%4)*100/3}% ${Math.floor(index/4)*100/3}%`}} aria-hidden="true"/>;}
export default function ControllerClient(){
 const [stage,setStage]=useState('title'),[code,setCode]=useState(''),[entry,setEntry]=useState(''),[name,setName]=useState(''),[character,setCharacter]=useState('julian'),[snapshot,setSnapshot]=useState<any>(null),[sessions,setSessions]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[connected,setConnected]=useState(false),[held,setHeld]=useState(''),[running,setRunning]=useState(false),[mode,setMode]=useState('solo'),[humanCount,setHumanCount]=useState(2),[voice,setVoice]=useState(true),[recipient,setRecipient]=useState(''),[sosPreset,setSosPreset]=useState('come_get_me');
 const input=useRef({x:0,y:0,run:false}),seq=useRef(0),current=useRef(''),lastSuccess=useRef(0),view=useRef<any>(null);
 async function api(path:string,body?:any,keepalive=false){const response=await fetch('/api/control'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store',keepalive,signal:keepalive?undefined:AbortSignal.timeout(5000)});const data:any=await response.json();if(!response.ok)throw new Error(messages[data.error]||data.error||'Unable to connect.');return data;}
 function accept(s:any){view.current=s;setSnapshot(s);seq.current=Math.max(seq.current,s.self?.seq||0,s.unreal?.hunt?.seq||0);lastSuccess.current=Date.now();setConnected(true);}
 function open(c:string){current.current=c;seq.current=0;view.current=null;input.current={x:0,y:0,run:false};setSnapshot(null);setError('');setCode(c);setEntry(c);setHeld('');setRunning(false);history.replaceState(null,'',`/?code=${c}`);}
 useEffect(()=>{const c=new URL(location.href).searchParams.get('code')?.toUpperCase();if(c&&/^[A-Z2-9]{8}$/.test(c))open(c);},[]);
 useEffect(()=>{if(code)return;let cancelled=false;const refresh=()=>api('').then(r=>{if(!cancelled){setSessions(r.sessions);setError('');}}).catch(()=>{if(!cancelled)setError('Unable to reach the event computer. Refresh to retry.');});refresh();const timer=setInterval(refresh,3000);return()=>{cancelled=true;clearInterval(timer);};},[code]);
 useEffect(()=>{if(!code)return;let cancelled=false,timer:any;async function poll(){try{const s=await api('/'+code);if(!cancelled&&current.current===s.code){accept(s);setError('');}}catch(e){if(!cancelled){setConnected(false);setError((e as Error).message);}}finally{if(!cancelled)timer=setTimeout(poll,650);}}poll();return()=>{cancelled=true;clearTimeout(timer);};},[code]);
 function transmit(stop=false){const s=view.current;if(s?.unreal?.mode==='survival-hunt')return;if(!s?.self||!current.current)return;if(!stop&&(!s.hostOnline||!s.unreal?.ready||s.settings.phase!=='playing'||Date.now()-lastSuccess.current>3500))return;void api('/'+current.current+'/input',{seq:++seq.current,...(stop?{x:0,y:0,run:false}:input.current)},stop).catch(()=>{setConnected(false);});}
 function stop(){input.current={x:0,y:0,run:false};setHeld('');setRunning(false);transmit(true);}
 useEffect(()=>{if(!snapshot?.self||stage!=='controller')return;const timer=setInterval(()=>{if(document.visibilityState==='visible')transmit();},120);const blur=()=>stop();const visibility=()=>{if(document.visibilityState!=='visible')stop();};window.addEventListener('blur',blur);window.addEventListener('pagehide',blur);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);window.removeEventListener('blur',blur);window.removeEventListener('pagehide',blur);document.removeEventListener('visibilitychange',visibility);stop();};},[code,snapshot?.self?.character,stage]);
 const roster=snapshot?.roster||CONTROLLER_ROSTER,selected=roster.find((c:any)=>c.id===character)||roster[0],self=snapshot?.self,actor=snapshot?.unreal?.actors?.find((a:any)=>a.character===self?.character),online=Boolean(connected&&snapshot?.hostOnline&&snapshot?.unreal?.ready&&snapshot?.settings?.phase==='playing'&&actor),hunt=snapshot?.unreal?.hunt,castReady=Boolean(actor&&hunt);
 useEffect(()=>{if(!online)stop();},[online]);
 useEffect(()=>{if(stage==='title'||!self)return;if(snapshot.settings.phase==='playing'&&['waiting','mode','choose'].includes(stage))setStage('loading');if(stage==='loading'&&castReady)setStage('controller');if(stage==='controller'&&snapshot.settings.phase==='lobby')setStage('waiting');},[stage,self?.character,snapshot?.settings?.phase,castReady]);
 function announce(c:any){if(voice&&'speechSynthesis' in window){window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(c.name);utterance.rate=.88;window.speechSynthesis.speak(utterance);}}
 function selectCharacter(c:any){setCharacter(c.id);announce(c);}
 function enter(){setError('');if(!code){if(sessions[0])open(sessions[0].code);else return;}if(self){setCharacter(self.character);setName(self.name);}if(self&&snapshot?.settings.phase==='playing')setStage('loading');else if(snapshot?.playerCount>0&&!self?.isHost)setStage('choose');else {if(self?.isHost){setMode(snapshot.settings.mode==='multiplayer'&&snapshot.settings.humanCount===12&&snapshot.playerCount===1?'solo':snapshot.settings.mode);setHumanCount(Math.max(2,snapshot.settings.humanCount));}setStage('mode');}}
 async function claim(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let s=self?await api('/'+code+'/choose',{character}):await api('/'+code+'/join',{name,character});if(s.self.isHost)s=await api('/'+code+'/configure',{mode,humanCount:mode==='solo'?1:humanCount});accept(s);setStage('waiting');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function action(op:string){setBusy(true);setError('');try{const s=await api('/'+code+'/'+op,{});accept(s);setStage(op==='start'?'loading':'mode');if(op==='lobby'){setMode(s.settings.mode);setHumanCount(Math.max(2,s.settings.humanCount));setCharacter(s.self.character);setName(s.self.name);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decide(action:string,room?:string){setBusy(true);setError('');try{await api('/'+code+'/decision',{seq:++seq.current,runId:snapshot.settings.runId,action,...(room?{room}:{})});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function sendHelp(target:string){setBusy(true);setError('');try{await api('/'+code+'/help',{runId:snapshot.settings.runId,recipient:target,preset:sosPreset});accept(await api('/'+code));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function answerHelp(id:number,acceptHelp:boolean){setBusy(true);setError('');try{await api('/'+code+'/answer-help',{runId:snapshot.settings.runId,id,accept:acceptHelp});accept(await api('/'+code));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function press(e:React.PointerEvent<HTMLButtonElement>,id:string,x:number,y:number){if(!online)return;e.currentTarget.setPointerCapture(e.pointerId);input.current={...input.current,x,y};setHeld(id);transmit();}
 function release(){input.current={...input.current,x:0,y:0};setHeld('');transmit();}
 const canHost=!snapshot?.playerCount||self?.isHost,humanTarget=snapshot?.settings?.humanCount||1;
 const peers=(snapshot?.players||[]).filter((p:any)=>p.character!==self?.character&&snapshot?.living?.includes(p.character)),chosenPeer=peers.some((p:any)=>p.character===recipient)?recipient:peers[0]?.character||'',sentThisRound=(snapshot?.messages||[]).some((m:any)=>m.sender===self?.character&&m.round===hunt?.round);
 return <div className={`haunted-game stage-${stage}`}>
 <img className="mansion-backdrop" src="/art/mansion-opening.webp" alt="A moonlit haunted museum mansion, its doors glowing through the mist" fetchPriority="high"/><div className="mansion-shade"/>
 <header className="game-topbar"><button className="game-wordmark" onClick={()=>{stop();setStage('title');}} aria-label="Return to title">HAUNTED GALLERY</button><span>{stage==='title'?'SCALEBEACON GAMES':`SESSION ${code||'…'}`}</span><button className="sound-switch" aria-label={voice?'Mute character names':'Speak character names'} aria-pressed={voice} onClick={()=>{setVoice(!voice);if(voice&&'speechSynthesis' in window)window.speechSynthesis.cancel();}}>{voice?<Volume2 size={19}/>:<VolumeX size={19}/>}</button></header>
 <main className="game-surface">
 {stage==='title'?<section className="title-scene"><p className="title-kicker">AN INVITATION TO THE UNKNOWN</p><h1>HAUNTED<span>GALLERY</span></h1><p className="title-line">The doors are open.<br/>They won’t stay that way.</p><button className="game-primary enter-button" onClick={enter} disabled={!code&&!sessions.length}>{self&&snapshot?.settings.phase==='playing'?'Resume your character':'Enter the gallery'}<ArrowRight size={20}/></button>{!code&&!sessions.length&&<p className="opening-status">Waiting for the event computer to connect.</p>}<details className="code-entry"><summary>Have a session code?</summary><form onSubmit={e=>{e.preventDefault();if(/^[A-Z2-9]{8}$/.test(entry)){open(entry);setStage('mode');}else setError('Enter the eight-character code from the main screen.');}}><input aria-label="Session code" value={entry} onChange={e=>setEntry(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))} maxLength={8} placeholder="SESSION CODE"/><button type="submit">Connect</button></form></details><p className="opening-note">Unreal survival-hunt prototype</p></section>:
 !snapshot?<section className="loading-scene"><LoaderCircle className="spin"/><h1>{error?'Connection interrupted':'Opening the doors…'}</h1><p>{error||'Connecting to the event computer.'}</p><button onClick={()=>setStage('title')}>Back to title</button></section>:
 stage==='mode'?<section className="mode-scene"><p className="eyebrow">YOUR NIGHT. YOUR CHOICE.</p><h1>How will you enter?</h1><div className="mode-options"><button className={`mode-option ${mode==='solo'?'selected':''}`} disabled={!canHost} onClick={()=>setMode('solo')}><UserRound/><strong>Solo</strong><span>You + 11 computer survivors</span>{mode==='solo'&&<Check size={18}/>}</button><button className={`mode-option ${mode==='multiplayer'?'selected':''}`} disabled={!canHost} onClick={()=>setMode('multiplayer')}><Users/><strong>Multiplayer</strong><span>Bring your people. Fill with computers.</span>{mode==='multiplayer'&&<Check size={18}/>}</button></div>{mode==='multiplayer'&&<label className="player-number">Human players, including you<select value={humanCount} disabled={!canHost} onChange={e=>setHumanCount(Number(e.target.value))}>{Array.from({length:11},(_,i)=>i+2).map(n=><option key={n} value={n}>{n} people · {12-n} computers</option>)}</select></label>}<button className="game-primary" onClick={()=>{if(self){setName(self.name);setCharacter(self.character);}setStage('choose');}}>Choose your character<ArrowRight size={18}/></button><p className="prototype-note">Prototype: choose rooms, evade hunters and escape. Personal phone video and cinematic characters are not connected yet.</p></section>:
 stage==='choose'?<section className="selection-scene"><div className="selection-heading"><button className="text-button" onClick={()=>setStage(canHost?'mode':'title')}><ChevronLeft size={18}/>Back</button><span>CHOOSE YOUR SURVIVOR</span></div><div className="selection-layout"><div className="character-stage" key={selected.id}><Portrait index={selected.index} className="character-entrance"/><div className="character-name"><span>{String(selected.index+1).padStart(2,'0')} / 13</span><h1>{selected.name}</h1><button className="text-button" onClick={()=>announce(selected)}><Volume2 size={15}/>Hear name</button></div></div><div className="cast-panel"><div className="cast-grid" aria-label="Available characters">{roster.map((c:any)=><button type="button" key={c.id} disabled={c.taken&&c.id!==self?.character} className={`cast-card ${character===c.id?'selected':''}`} onClick={()=>selectCharacter(c)} aria-pressed={character===c.id} aria-label={`${c.name}${c.taken&&c.id!==self?.character?', claimed':''}`}><Portrait index={c.index}/><span>{c.name}</span>{c.taken&&c.id!==self?.character&&<small>CLAIMED</small>}</button>)}</div><form onSubmit={claim} className="claim-form">{!self&&<><label htmlFor="player-name">Your name</label><input id="player-name" required minLength={2} maxLength={32} autoComplete="nickname" value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?"/></>}<button className="game-primary" disabled={busy||Boolean(selected.taken&&selected.id!==self?.character)}>{busy?'Reserving your place…':`Choose ${selected.name.split(' ')[0]}`}<ArrowRight size={18}/></button></form><p className="prototype-note">Concept portraits and animated previews. In-game characters currently use temporary 3D models. Name readout uses your device’s voice.</p></div></div></section>:
 stage==='waiting'?<section className="lobby-scene"><p className="eyebrow">{snapshot.settings.mode==='solo'?'SOLO SURVIVAL HUNT':'MULTIPLAYER LOBBY'}</p><h1>{self?.isHost?'Your party is ready.':'Your place is reserved.'}</h1><div className="lobby-cast"><Portrait index={roster.find((c:any)=>c.id===self?.character)?.index||0}/><div><h2>{roster.find((c:any)=>c.id===self?.character)?.name}</h2><p>{self?.name}</p><button className="text-button" onClick={()=>{setCharacter(self.character);setStage('choose');}}>Change character</button></div></div><div className="party-counts"><div><strong>{snapshot.playerCount}/{humanTarget}</strong><span>Human players</span></div><div><strong>{12-humanTarget}</strong><span>Computer survivors</span></div></div>{snapshot.settings.mode==='multiplayer'&&<div className="invite-block"><img src={'/api/qr?code='+code} alt="Join this Haunted Gallery session QR code"/><div><span>INVITE YOUR PLAYERS</span><strong>{code}</strong><p>Scan on each phone and choose a different character.</p></div></div>}<p className="connection-status">{snapshot.hostOnline&&snapshot.unreal?.ready?'Event computer connected':'Waiting for Unreal to be ready'}</p>{self?.isHost?<><button className="game-primary" disabled={busy||snapshot.playerCount!==humanTarget||!snapshot.hostOnline||!snapshot.unreal?.ready} onClick={()=>action('start')}>{busy?'Starting…':snapshot.playerCount===humanTarget?'Start hunt':`Waiting for ${humanTarget-snapshot.playerCount} more player${humanTarget-snapshot.playerCount===1?'':'s'}`}<ArrowRight size={18}/></button><button className="text-button" onClick={()=>{setMode(snapshot.settings.mode);setHumanCount(Math.max(2,humanTarget));setStage('mode');}}>Change play mode</button></>:<p>Waiting for {snapshot.hostName} to start.</p>}<p className="prototype-note">Engineering test: Unreal currently displays one character’s 3D view on the event computer. This phone sends private room choices. Individual phone video is unfinished.</p></section>:
 stage==='loading'?<section className="loading-scene"><LoaderCircle className="spin" size={38}/><p className="eyebrow">ENTERING THE MANSION</p><h1>Taking your places.</h1><p>{actor?'Your character is connected':'Waiting for your character'}</p><p className="prototype-note">Waiting for the actual characters on the event computer.</p>{self?.isHost&&<button className="text-button" disabled={busy} onClick={()=>action('lobby')}>Return to lobby</button>}</section>:
 <section className="controller-scene"><div className="controller-identity"><div><p className="eyebrow">{self?.name} · SURVIVAL HUNT</p><h1>{roster.find((c:any)=>c.id===self?.character)?.name}</h1></div><span className={`connection ${online?'':'offline'}`}>{online?'Connected':'Reconnecting…'}</span></div>
 <p className="prototype-note" role="status">3D gameplay is currently on the Shadow PC. Your personal phone video is not connected yet. This is the room-choice engineering test.</p>
 <div className="personal-location"><span>YOUR PRIVATE VIEW · ROUND {hunt?.round||1}</span><strong>{hunt?.roomName||'Connecting to Unreal'}</strong><small>{hunt?.role==='zombie'?'You have turned. Choose where to hunt.':hunt?.role==='escaped'?'You escaped alive.':hunt?.role==='trapped'?'The hunt has ended.':'Survive. Find a way out.'}</small></div>
 <p className="controller-cue" aria-live="polite">{hunt?.message||'Waiting for the hunt.'}</p>
 {hunt?.role==='zombie'&&<p className="prototype-note">Still alive: {(snapshot?.living||[]).map((id:string)=>roster.find((c:any)=>c.id===id)?.name).filter(Boolean).join(', ')||'No survivors remain'}. Their rooms and private messages are hidden.</p>}
 {hunt?.role==='survivor'&&<section className="sos-panel" aria-label="Private phone messages"><div className="sos-heading"><strong>PRIVATE MESSAGES</strong><span>Only you and the recipient can see these.</span></div>
 {(snapshot?.messages||[]).filter((m:any)=>m.recipient===self?.character).map((m:any)=><div className="sos-message" key={m.id}><strong>{roster.find((c:any)=>c.id===m.sender)?.name||'A guest'}</strong><p>{sosText[m.preset]||'Help me'} · {roomNames[m.room_snapshot]||m.room_snapshot}</p><small>Room when sent · round {m.round} · {m.status==='pending'?'Awaiting your answer':m.status==='accepted'?'You agreed to help':'You declined'}</small>{m.status==='pending'&&<div className="sos-actions"><button disabled={!online||busy} onClick={()=>answerHelp(m.id,true)}>I’m coming</button><button disabled={!online||busy} onClick={()=>answerHelp(m.id,false)}>Ignore</button></div>}</div>)}
 {(snapshot?.messages||[]).filter((m:any)=>m.sender===self?.character).map((m:any)=><div className="sos-message sent" key={m.id}><strong>To {roster.find((c:any)=>c.id===m.recipient)?.name||'guest'}</strong><p>{sosText[m.preset]} · {roomNames[m.room_snapshot]||m.room_snapshot}</p><small>{m.status==='accepted'?'They agreed to help':m.status==='ignored'?'They declined':'Waiting for a reply'}</small></div>)}
 {peers.length>0&&hunt?.phase==='choice'&&!sentThisRound&&<div className="sos-compose"><label htmlFor="sos-recipient">Ask a guest for help</label><select id="sos-recipient" value={chosenPeer} onChange={e=>setRecipient(e.target.value)}>{peers.map((p:any)=><option key={p.character} value={p.character}>{roster.find((c:any)=>c.id===p.character)?.name||p.name}</option>)}</select><label htmlFor="sos-preset">Message</label><select id="sos-preset" value={sosPreset} onChange={e=>setSosPreset(e.target.value)}>{Object.entries(sosText).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><button disabled={!online||busy||!chosenPeer} onClick={()=>sendHelp(chosenPeer)}>Send private SOS</button><small>Your current room is attached automatically. One message per round.</small></div>}
 <p className="sos-explain">A reply does not move anyone or earn points. Your guest must travel to help in the mansion.</p></section>}
 {hunt?.moving?<p>Your character is running to {hunt.destination}. The Unreal camera follows from above.</p>:<div className="mode-options" aria-label="Private room choices">{hunt?.options?.map((o:any)=><button key={o.id} className={`mode-option ${hunt.choice===o.id?'selected':''}`} disabled={!online||busy||(hunt.seq??0)<(self?.seq??0)} onClick={()=>decide('room',o.id)}><strong>{o.id===hunt.room?'Stay here':o.name}</strong><span>{o.id===hunt.room?(hunt.role==='zombie'?'Search this room':'Remain hidden'):'Your character runs there after choices lock'}</span>{hunt.choice===o.id&&<Check size={18}/>}</button>)}</div>}
 {hunt?.camera&&<div className="invite-block"><div><span>ANTIQUE CAMERA · BATTERIES INTACT</span><p>{hunt.recharge>0?`Recharging · ${hunt.recharge.toFixed(1)}s`:'Ready for a photograph'}</p><button className="game-primary" disabled={!online||busy||!hunt.canPhoto||(hunt.seq??0)<(self?.seq??0)} onClick={()=>decide('photo')}>Take photo</button></div></div>}
 <p className="prototype-note">{hunt?.phase==='blocked'?'A character could not finish a route. The test is paused for repair.':hunt?.finished?'This hunt has ended. Return to the lobby for another game.':`${hunt?.phase||'Connecting'} · ${Math.ceil(hunt?.remaining||0)}s`} · Room locations and private messages stay hidden from other guests.</p>
 {self?.isHost&&<button className="text-button" disabled={busy} onClick={()=>action('lobby')}>End hunt and return everyone to lobby</button>}</section>}

 {error&&<p role="alert" className="game-error">{error}</p>}
 </main><div className="game-bottomline"><span>SCALEBEACON GAMES</span><span>Escape alive.</span></div>
 </div>;
}
